(define (sum_of_squares x y)
  (+ (square x) (square y))
)

(define (task3 x y z)
  (define maxA (max x y))
  (define maxB (max y z))
  (define maxC (max x z))
  (define diff_between_A_B (- maxA maxB))
  (if (= 0 diff_between_A_B)
      (sum_of_squares maxA maxC)
      (sum_of_squares maxA maxB)
  )
)

(define (task3_cond x y z)
  (cond ((or (> x y) (> x z)) (sum_of_squares x (max y z)))
        ((> y z) (sum_of_squares y (max x z)))
        (else    (sum_of_squares z (max x y)))
  )
)
